<?php
declare(strict_types=1);

namespace App\Middleware;

use Cake\Http\Middleware\CsrfProtectionMiddleware;
use Cake\Utility\Hash;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Psr\Http\Server\RequestHandlerInterface;

/**
 * Standard CSRF protection, with added backward compatibility
 * for tokens generated by CakePHP 3.10.
 */
class LegacyCsrfProtectionMiddleware extends CsrfProtectionMiddleware
{
    /**
     * Performs original CSRF check + force rotating old tokens to the new format
     */
    public function process(ServerRequestInterface $request, RequestHandlerInterface $handler): ResponseInterface
    {
        $method = $request->getMethod();
        $hasData = in_array($method, ['PUT', 'POST', 'DELETE', 'PATCH'], true)
            || $request->getParsedBody();

        if (!$hasData) {
            $cookies = $request->getCookieParams();
            $cookieData = Hash::get($cookies, $this->_config['cookieName']);

            if (is_string($cookieData) && $this->isHexadecimalToken($cookieData)) {
                // Force parent CsrfProtectionMiddleware to regenerate a new token
                unset($cookies[ $this->_config['cookieName'] ]);
                $request = $request->withCookieParams($cookies);
            }
        }

        return parent::process($request, $handler);
    }

    private function isCakePHP310Token(string $token): bool
    {
        return preg_match('/^[a-f0-9]{128}$/', $token) === 1;
    }

    protected function isHexadecimalToken(string $token): bool
    {
        // Allow tokens generated by CakePHP 3.10, too
        return parent::isHexadecimalToken($token) || $this->isCakePHP310Token($token);
    }

    protected function _verifyToken(string $token): bool
    {
        if ($this->isCakePHP310Token($token)) {
            // Tokens generated by CakePHP 3.10 have no particular verification mechanism
            return true;
        } else {
            return parent::_verifyToken($token);
        }
    }
}
