# Manticore reads its config by calling a Cake shell
# Cake shell executes an SQL request to check which languages have sentences
# So the database MariaDB is a dependency of Manticore
[Unit]
After=mariadb.service
Requires=mariadb.service
