---
# Tasks specyfing commom tasks for all servers

- name: Ensure git is installed
  apt:
    name: git
    state: latest
    force: yes

- name: Download Transifex client
  when: deploy_for == 'dev'
  get_url:
    url: https://github.com/transifex/cli/releases/download/v1.6.17/tx-linux-amd64.tar.gz
    dest: /tmp/tx-linux-amd64.tar.gz

- name: Uncompress Transifex client
  when: deploy_for == 'dev'
  unarchive:
    src: /tmp/tx-linux-amd64.tar.gz
    dest: /usr/local/bin/
    include: tx
    remote_src: yes

- name: Remove Transifex archive
  when: deploy_for == 'dev'
  file:
    path: /tmp/tx-linux-amd64.tar.gz
    state: absent

- name: Install other packages needed for development
  apt:
    name: ['gettext', 'python3-jinja2', 'python3-yaml']
  when: deploy_for == 'dev'
