---

- name: Temporarily stop unattended upgrades
  systemd_service:
    name: unattended-upgrades
    state: stopped

- name: Copy sources.list for apt
  template:
    src: sources.list
    dest: /etc/apt/sources.list
    owner: root
    group: root
    mode: 0644
    backup: yes
  register: result

- name: Update apt cache
  apt:
    update_cache: yes
  when: result is changed

# The base debian box has /etc/systemd/system/set-grub-install-device.service,
# a thing that is here to prevent "apt upgrade" from asking where to install
# GRUB. That thing is designed to start just once during the very first boot.
# However, for some reason, it sometimes fails with this error:
#
#   debconf: DbDriver "config": /var/cache/debconf/config.dat is locked by another process: Resource temporarily unavailable
#
# So we check if it already executed successfully, and it it did not,
# we execute it again.
- name: Make sure GRUB is configured
  shell: systemctl is-enabled set-grub-install-device && systemctl is-failed set-grub-install-device && systemctl restart set-grub-install-device || true

- name: Update all packages
  apt:
    upgrade: yes

- name: List installed kernels
  shell: ls -1 /lib/modules | sort -rV
  register: installed_kernels

- name: Reboot unless running latest kernel
  reboot:
  when: installed_kernels.stdout_lines | length > 1 and installed_kernels.stdout_lines[0] != ansible_facts['kernel']

- name: List unused kernels
  shell: ls -1 /lib/modules | grep -v "^$(uname -r)$" | sed 's,^,linux-image-,'
  register: unused_kernels

- name: Remove unused kernels
  apt:
    name: "{{unused_kernels.stdout_lines}}"
    state: absent
    purge: true
  when: unused_kernels.stdout_lines | length > 0

- name: Add extra PATH directories
  copy:
    dest: /etc/profile.d/custom-path.sh
    content: 'PATH=$PATH:{{code_dir}}/bin:{{code_dir}}/vendor/bin'

- name: Prevent sudo from complaining about the new hostname
  replace:
    dest: /etc/hosts
    regexp: "{{ansible_hostname}}"
    replace: 'tatovm'

- name: Change hostname to tatovm
  hostname:
    name: tatovm
