---
#Tasks for setting up nginx

- name: Uninstall apache2
  apt:
    name: apache2
    state: absent
    purge: yes
    autoremove: yes

- name: Install nginx
  apt:
    name: ['nginx', 'libnginx-mod-http-headers-more-filter']
    state: latest

- name: Remove default nginx configurations
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Create configuration directories
  file:
    path: '{{ item }}'
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled

- name: Copy Tatoeba vhost
  template:
    src: '{{ nginx_config_file }}'
    dest: /etc/nginx/sites-available/tatoeba.org
    owner: www-data
    group: root
    mode: 0644
    backup: yes

- name: Enable Tatoeba vhost
  file:
    state: link
    force: yes
    src: /etc/nginx/sites-available/tatoeba.org
    dest: /etc/nginx/sites-enabled/tatoeba

- name: Restart nginx
  service:
    name: nginx
    state: restarted
    enabled: yes
