; actions not available for guests or some users

[Activities]
translate_sentences, adopt_sentences = admin, corpus_maintainer, advanced_contributor, contributor

[Audio]
import, save, delete = admin
save_settings = admin, corpus_maintainer, advanced_contributor, contributor

[ReportContent]
* = admin, corpus_maintainer, advanced_contributor, contributor

[Reviews]
* = admin, corpus_maintainer, advanced_contributor, contributor

[Favorites]
* = admin, corpus_maintainer, advanced_contributor, contributor

[Links]
* = admin, corpus_maintainer, advanced_contributor

[Imports]
* = admin

[Licensing]
* = admin, corpus_maintainer, advanced_contributor, contributor

[PrivateMessages]
* = admin, corpus_maintainer, advanced_contributor, contributor

[SentenceAnnotations]
* = admin, corpus_maintainer, advanced_contributor, contributor

[SentenceComments]
hide_message, unhide_message = admin
save, edit, delete_comment = admin, corpus_maintainer, advanced_contributor, contributor

[Sentences]
edit_correctness, mark_unreliable = admin
add, delete, adopt, let_go     = admin, corpus_maintainer, advanced_contributor, contributor
add_an_other_sentence, import  = admin, corpus_maintainer, advanced_contributor, contributor
edit_license, save_translation = admin, corpus_maintainer, advanced_contributor, contributor
change_language, edit_sentence = admin, corpus_maintainer, advanced_contributor, contributor

[SentencesLists]
* = admin, corpus_maintainer, advanced_contributor, contributor

[Tags]
* = admin, corpus_maintainer, advanced_contributor

[CategoriesTree]
* = admin, corpus_maintainer, advanced_contributor

[Transcriptions]
* = admin, corpus_maintainer, advanced_contributor, contributor

[User]
* = admin, corpus_maintainer, advanced_contributor, contributor

[Users]
* = admin

[UsersLanguages]
* = admin, corpus_maintainer, advanced_contributor, contributor

[Vocabulary]
* = admin, corpus_maintainer, advanced_contributor, contributor

[Wall]
hide_message, unhide_message = admin
save, save_inside, edit, delete_message = admin, corpus_maintainer, advanced_contributor, contributor
