; actions available to everyone, even guests

Activities = improve_sentences, translate_sentences_of

ApiV0 = search, sentence

Audio = of, index, download

Reviews = of

Contributions = *

Exports = add, get, download

Pages = *

Favorites = of_user

S = *

SentenceAnnotations = last_modified

Sentences = index, show, search, advanced_search, of_user, random, go_to_sentence, several_random_sentences, get_neighbors_for_ajax, show_all_in, with_audio

SentencesLists = index, show, of_user, download, search, collaborative

SentenceComments = index, show, of_user, on_sentences_of_user

Stats = *

Tags = show_sentences_with_tag, view_all, search, autocomplete

Tools = *

Transcriptions = view, of

User = profile

Users = all, search, show, login, check_login, logout, register, new_password, check_username, check_email, for_language, login_dialog_template

Vocabulary = of

Wall = index, show_message, messages_of_user

AngularTemplates = *
